logging:
  config: classpath:logback/logback-spring.xml
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

jwt:
  access-header: access-token
  refresh-header: refresh-token
  secret: UGFya1N1bmdId2FuLXRpbC1kaWFyeS1zcHJpbmdib290UGFya1N1bmdId2FuLXRpbC1kaWFyeS1zcHJpbmdib290UGFya1N1bmdId2FuLXRpbC1kaWFyeS1zcHJpbmdib290Cg==
  access-token-validity-in-seconds: 1
  refresh-token-validity-in-seconds: 86400

spring:
  datasource:
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springboot_demo
    url: jdbc:mysql://localhost:3306/springboot_demo?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true