logging:
  config: classpath:logback/logback-spring.xml
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

jwt:
  access-header: access-token
  refresh-header: refresh-token
  secret: UGFya1N1bmdId2FuLXRpbC1kaWFyeS1zcHJpbmdib290UGFya1N1bmdId2FuLXRpbC1kaWFyeS1zcHJpbmdib290UGFya1N1bmdId2FuLXRpbC1kaWFyeS1zcHJpbmdib290Cg==
  access-token-validity-in-seconds: 1
  refresh-token-validity-in-seconds: 86400

spring:
  profiles:
    default: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
